version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: my_postgres
        environment:
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: my_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: your_pgadmin_email@example.com
            PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
        ports:
            - "5050:80"
        depends_on:
            - postgres

volumes:
    postgres_data:
